### ISSUE TITLE
Duplication of output cells in merge gui

### ISSUE THREAD

**Issue by martinal** [jupyter/nbdime#120]
The current drag-and-drop output handling in the merge gui will just insert copies of the output cells, with no way to undo, so you can end up with repeated instances of output cells you drag two times.

Adding a button to clear conflicting output is one way to solve this, useful also to quickly decide you don't need this output.

But maybe also add a check to avoid adding output cell twice in the merged output?

**Comment by vidartf** [comment]
My current plan is to:
 - Add a "Clear outputs" button on cells
 - Add a "Clear all outputs" button in header (remove all outputs in all cells)
 - Add a "Delete output" (trash can) drop zone during drag and drop so that added outputs can be removed.

Adding a uniqueness constrain should also be possible, but I'm a little concerned it might be problematic for certain corner cases.

**Comment by martinal** [comment]
Great, I think those buttons should cover all practical use cases.
