### ISSUE TITLE
Ad Hoc Support for "Track Changes" Like Functionality?

### ISSUE THREAD

**Issue by psychemedia** [jupyter/nbdime#251]
One of the workflow issues I have relates to collaborative production and review of notebooks for teaching/tutorial/documentation purposes, (another is annotating student completed templated notebooks for assessment or feedback).

When working with Office documents, *track changes* is the model we tend to use. So I was wondering to what extent the `nbdiff` code could be used to generate a "tracked changes" notebook, eg creating a notebook with unchanged cells then colour styled old/new cells. (So a changed cell would be in the tracked notebook as two adjacent cells - one for the original and one for the new version).

A reviewer could then inspect new content (eg student's answers) or delete unwanted changed cells (when reviewing collaborative documents), as well as adding new cells or annotation cells in the normal way.

Finally, on saving the notebook, it would make sense to be able to strip/clean away any metadata used to highlight the changed cells. (So maybe it would make sense to to: a) create a 'tracked changes" notebook; b) provide a toolbar to help work with such a notebook.)

**Comment by vidartf** [comment]
Hmm. I think a decent solution should be possible with some minor changes:

Previously when submitting articles with Office or Latex PDFs, I've included two versions: One clean, updated version, and one with the changes highlighted (e.g. by tracking). I think this pattern will probably work best for notebooks, in cases where the reviewer can not be relied on to have nbdime.

To generate a static webpage showing the diff, I tried to simply save the diff web view from firefox, and then reload that page after shutting down the server. This initially failed, because the javascript is set to remove the output if it fails to fetch the diff (actually it replaces it with any error feedback from the server) . After manually disabling this feature, the static view seemed to work!

As such, I think a static view is just a matter of :
 a. Changing the behavior on error OR
 b. Having an "Export" button on diff view that saves as static HTML/CSS/JS

Having a separate "in-notebook diff rendering" could possibly be done using the same machinery that does inline merge, but having this automatically cleaned is definitely not an ad-hoc job!

**Comment by psychemedia** [comment]
What I was thinking was something very crudely along the lines of:

    # create output notebook based on diffs between original and edited notebook
    trackedchanges=nb4.new_notebook()
    
    #iterate through cells
        # if not changed cell:
          # append unchanged cell to trackedchanges
        # else:
          # append old cell to trackedchanges, metadata style: red
          # append new cell to trackedchanges, metadata style: green

The output would be a notebook, rather than the HTML difference file. It'd be up to the user to then delete one or other of the appended cells and run something to strip the metadata styling to give a revised saved notebook.

**Comment by vidartf** [comment]
This is something you should be able to do using nbdime as a library. The relevant code points to use:

 - For getting diff, use `nbdime.diffing.diff_notebooks()`. Pass notebooks read by `nbformat.read`. E.g.
```python
a = nbformat.read(<filename A>, as_version=4)
b = nbformat.read(<filename B>, as_version=4)
d = diff_notebooks(a, b)
```
 - The looping requires some logic to keep indices correct, as the keys in the diff will be relative to notebook `a` (the base). See diff format entry in docs.
 - Stripping the metadata can be done purely with `nbformat`.

Hope this helps!

**Comment by vidartf** [comment]
There could/should possibly be a utility function in nbdime for helping to loop over a base/diff combination. Either just for API util, or possibly for internal use as well.

Signature could e.g. be:
```python
for base_entry, entry_diff in nbdime.util.iterate_list_with_diff(base, diff, path_of_list):
    if not entry_diff:
        # Unchanged
    else:
        remote_entry = nbdime.patch(base_entry, entry_diff)
```
For your example above, the `path_of_list` would simply be `['cells']`. Possibly we could make another entry on top which is simply `iterate_cells(base, diff)`.

**Comment by vidartf** [comment]
I'm closing this unless there are any further questions/suggestions/requests for things to do in the nbdime repo.
