### ISSUE TITLE
frontend-extension not working with jupyter-hub

### ISSUE THREAD

**Issue by wotanii** [jupyter/nbdime#337]
The front-end plugin doesn't seem to work in jupyter-hub. 

Here is what I have tried: 

I made a single-user dockerfile. Executing it directly works like a charm. But when I execute it via jupyterhub, nbdime's nbextension breaks. I suspect this is due to the routing of jupyter hub. 
I believe the problem is, that dockerhub doesn't forward the URL  to the server-extension. I hope it is possible to configure jupyterhub in such a way, that the server-extension works. 

### reproduction 

Here is my minimal working setup: 

Dockerfile: 

```
FROM jupyter/minimal-notebook:e1677043235c
RUN python3 -m pip install jupyterhub==0.8.0 nbdime
USER root
RUN nbdime reg-extensions --system
USER jovyan
```

execute it with:

`docker build -t tc .;and docker run -it --name cc --rm -p 8888:8888 tc` 

result (after clicking button "checkpoint diff" in a new notebook): 

![bildschirmfoto vom 2017-12-12 16-12-21](https://user-images.githubusercontent.com/4362465/33892324-cf146612-df58-11e7-87d3-64d4c378f7bc.png)

as expected: just an empty diff. 

But when I execute the same Dockerfile via the dockerspawner in jupyter hub, I get this instead after clicking the same button: 

![bildschirmfoto vom 2017-12-12 16-11-58](https://user-images.githubusercontent.com/4362465/33892290-b97f1766-df58-11e7-8e82-0771c3840626.png)

As you can see, the URL is different here: "user/bjoern" was added before "/nbdime/"

___

My Dockerhub is based on [jupyterhub-deploy-docker](https://github.com/jupyterhub/jupyterhub-deploy-docker).

The changes I made to jupyterhub-deploy-docker: in the folder "singleuser" is the Dockerfile form above. My version uses dockerhub 0.8.0 (0.8.1 doesn't seem to build for me) and Docker 1.17.03, so I removed the args before "FROM" and replaced them literal values.  Also I use a dummy-authenticator instead of  github-auth. I don't think, that any of my changes are responsible for breaking nbdime. 
___

**Comment by rkdarst** [comment]
Hi,

I had the same problem with jupyterhub + nbdime, but I don't think it's caused by the different URL: that's the standard jupyterhub URL prefix which is forwarded to the single-user server.  Note all per-user URLs are like that in jupyterhub.

I'm not using docker: instead, I am using batchspawner.  I noticed this in my single-user server logfiles:

```
[W 2018-03-24 04:51:19.490 SingleUserNotebookApp notebookapp:1459] Error loading server extension nbdime
    Traceback (most recent call last):
      File "/share/apps/jupyterhub/live/miniconda/lib/python3.6/site-packages/notebook/notebookapp.py", line 1454, in init_server_extensions
        func(self)
      File "/share/apps/jupyterhub/live/miniconda/lib/python3.6/site-packages/nbdime/__init__.py", line 18, in load_jupyter_server_extension
        _load_jupyter_server_extension(nb_server_app)
      File "/share/apps/jupyterhub/live/miniconda/lib/python3.6/site-packages/nbdime/webapp/nb_server_extension.py", line 195, in _load_jupyter_server_extension
        env.loader.searchpath.append(template_path)
    AttributeError: 'ChoiceLoader' object has no attribute 'searchpath'
```

I began digging in `nbdime/webapp/nb_server_extension.py` and saw that it has been changed lately (dec 5).  461fd660 is a relevant commit (newer than 0.4.1) that changes the exact lines with the error.

When I installed the latest `master` nbdime manually, I noticed it works in jupyterhub.  So whatever the problem was, it will be solved on the next release (hopefully).  I don't know what the root cause was or why this fixed it, so hopefully someone else can know what's going on and confirm things are good now.

Thanks for this tool (and all jupyter in general),

- Richard

**Comment by rkdarst** [comment]
Also, I would point out that this is dependent on jupyterhub: just like wotanii, this works when run directly as `jupyter notebook`, but not when launched from jupyterhub.  Same conda environment with same software inside.

I think the `loader` without `searchpath` came from the `notebook` package, proximate cause could have also been some sort of dependency issue.

**Comment by vidartf** [comment]
@rkdarst Thanks for the detective work! The PR that includes that commit (https://github.com/jupyter/nbdime/pull/339) does indeed indicate that this could be a problem for jupyterhub. We've been triaging issues and PRs in order to release a new version in the near future.

@wotanii Could you verify whether this issue is fixed on master or not (see http://nbdime.readthedocs.io/en/latest/installing.html#install-the-development-version)? If you do not have the opportunity to test the dev version, could you at least check the notebook server log to see if you are getting the same error message as that reported by @rkdarst ?

**Comment by wotanii** [comment]
Can confirm: It works now. 

what I have tested: I restarted the environment from the first comment and noted that problem still occurs.  Then I changed 

```
RUN python3 -m pip install jupyterhub==0.8.0 nbdime
```
to 
```
RUN python3 -m pip install jupyterhub==0.8.0
RUN python3 -m pip install -e git+https://github.com/jupyter/nbdime#egg=nbdime
```

and now it works like a charm inside jupyterhub.
