### ISSUE TITLE
Add option to ignore empty cells

### ISSUE THREAD

**Issue by AllanLRH** [jupyter/nbdime#359]
Would be nice with an option to ignore empty cells, both added and deleted.

I tend to create a bunch of empty cells at the bottom of my notebooks, in order to be able to scroll the bottom-most cell with content higher up the page, and sometimes I forget to delete the extra cells.

**Comment by vidartf** [comment]
I think this would probably best be achieved by a ***git filter***. In addition to keeping the view of the diff clean, this would actually prevent the extra empty cells from entering the repo!

See https://git-scm.com/docs/gitattributes#_code_filter_code for further details, or https://github.com/kynan/nbstripout for an example of a git filter working on notebooks. Since #335, nbdime should take your filter settings into account when showing diffs.

**Comment by vidartf** [comment]
Closing as answered (use filter). If anybody has any further arguments for adding this to nbdime instead, feel free to comment on the issue!
