### ISSUE TITLE
404 GET /nbdime/static/

### ISSUE THREAD

**Issue by stas00** [jupyter/nbdime#405]
Since updating to notebook 5.6.0, using the dev build of nbdime,  I started getting these in the logs:

```
[W 15:05:40.567 NotebookApp] 404 GET /nbdime/static/43bb4cbf1d0ecfdb1309e4cb67264f35.ttf (127.0.0.1) 5.12ms referer=http://localhost:8888/nbdime/git-difftool?base=test.ipynb
[W 15:05:40.571 NotebookApp] 404 GET /nbdime/static/5a0856eb52623ae94b09dbbf31a27b95.ttf (127.0.0.1) 1.38ms referer=http://localhost:8888/nbdime/git-difftool?base=test2.ipynb
```

and also it seems to block notebook reloads, and takes a long time before getting the desired:
`Adapting to protocol v5.1 for kernel 9cfcc980-bfd7-41e4-b6df-6fcac3125e1e`
and the notebook can be run. [It hits the behavior described [here](https://github.com/jupyter/notebook/issues/3764)]

this is with nbdime built as:

`pip3 install -e git+https://github.com/jupyter/nbdime#egg=nbdime`

Once I rollback to the non-dev version of nbdime, everything is fine.

This is on python 3.6.6
Thanks

**Comment by vidartf** [comment]
Thanks for the report!

The 404 I think is a proper issue (path issue for loading font resource), but it should only result in the diff view using a fallback monospace font (browser/OS dependent). I'll work on a fix.

You should be able to get rid of the `Adapting to protocol v5.1 for kernel` message by updating `ipykernel`. Not sure if this will fix any of your other issues though.

The slow notebook reload should hopefully be unrelated to nbdime, but there might be an issue. Would you mind opening up the "Network" tab in your browser's developer tools and refreshing the notebook? If you see any slow requests to either `http://localhost:8888/nbextensions/nbdime/index.js` or `http://localhost:8888/nbdime/api/isgit`, we should profile it further. Otherwise, it seems unlikely that nbdime is involved.

**Comment by vidartf** [comment]
@stas00 Finally got around to checking out the 404s. For me, these errors also appear when viewing a normal notebook (>=5.6) with math in a markdown cell (i.e. without the nbdime extension). As such, I think these errors are unrelated to nbdime, and are simply an artifact. Do you agree?

**Comment by vidartf** [comment]
Closing for now. Will reopen if it becomes clear this was an nbdime issue after all.
