### ISSUE TITLE
Question: nbdime config-git and virtualenvs

### ISSUE THREAD

**Issue by chmp** [jupyter/nbdime#437]
I only recently started using nbdime, so I hope I did not overlook something obvious. My questions concerns the use of `nbdime` inside virtualenvs.

I install all my packages, including jupyter & nbdime, inside a virtualenv. However, after using `config-git`, my git config will contain references to the nbdime tools inside PATH. E.g., 

```
[diff "jupyternotebook"]
	command = git-nbdiffdriver diff
```

This way, `git diff` will fail, when run outside the current virtualenv. I worked around this issue by manually including the full path to the tools. E.g., 

```
[diff "jupyternotebook"]
	command = /full_path_to_my_venv/bin/git-nbdiffdriver diff
```

My question now is: What is the preferred way to install nbdime in a virtualenv and use it with git? Would you recommend to include the full path?

**Comment by QuinRiva** [comment]
I'd also like to know the answer to this.  My assumption is that because it's integrating with Jupyter and I'd want to be able to call a git-diff regardless of which kernal I'm using - it'd need to be installed under the base installation rather than a virtual environment.

I'm not sure if this is the correct approach - but I launch Jupyter from the base environment and then select the virtual environment within Jupyter.

**Comment by minrk** [comment]
For now, I think the solution to this is to document that you need to specify the absolute path in your git config if you want to install nbdime and use it from a location not on your PATH (e.g. a dedicated env for nbdime while working on another env). This would go under the [manual registration](https://nbdime.readthedocs.io/en/latest/vcs.html#manual-registration) section of the docs.

We can discuss whether the default behavior should be to register the absolute path or the base name, but my inclination is not, because it can add fragility and surprise as you work with new envs where nbdime *is* installed.

The final option is an opt-in flag to `config-get` that registers absolute paths instead of the base name, but ultimately this is just a shortcut to the same manual config above.

**Comment by chmp** [comment]
Thanks for clarifying. I am now less and less convinced that using the project venv path is a good idea, as it will indeed break unexpectedly when the venv is moved or deleted. For one of my own tools (not notebook related), I am currently experimenting with [pex](https://github.com/pantsbuild/pex) to put the tool with its full venv into my path. I'll see how it would look like with nbdime and report back.

**Comment by vidartf** [comment]
I'm closing this as answered. If there are still some unclear points, or if you want to continue the discussion, feel free to comment, and I will reopen the issue!
