### ISSUE TITLE
add syntax highlighting to code cells in nbshow output 

### ISSUE THREAD

**Issue by lebedov** [jupyter/nbdime#456]
It would be nice to add syntax highlighting to code cells in nbshow output using something like pygments (proof-of-concept available [here](https://gist.github.com/lebedov/bf24781b891de609f1a930132941211e)).

**Comment by vidartf** [comment]
Hi! That could be a very nice feature, indeed. While I have a bit of hesitation to put too many features into a "side-tool" of nbdime, it does look nice and compact. Do you want to open a PR? The best implementation would probably be a function call before [this call](https://github.com/jupyter/nbdime/blob/435ce3b2d96f8194ea60448b4de00a47a394a7c6/nbdime/prettyprint.py#L616). It should ideally take an argument specifying the language, so that the correct lexer can be chosen (I can help in threading that argument correctly through the call chain).

**Comment by lebedov** [comment]
PR created. Please update to pass the source language through the call chain so as to select the correct lexer (which is currently hard coded to Python).

**Comment by vidartf** [comment]
Closed by #466.
