### ISSUE TITLE
Conflicting python version commands

### ISSUE THREAD

**Issue by timkpaine** [jupyter/nbdime#528]
[ensure_python(('2.7', '>=3.4'))](https://github.com/jupyter/nbdime/blob/master/setup.py#L22)
[setup_args['python_requires'] = '>=3.5'](https://github.com/jupyter/nbdime/blob/master/setup.py#L140)

**Comment by vidartf** [comment]
Right, that is mostly on purpose:
- the `ensure_python` call is a sanity check saying "I refuse to install if you don't have at least this"
- the `python_requires` version is what is officially supported (but we give you the ability to try to install it on other versions since it might work).

As modern versions of pip (that check `python_requires` when resolving) are more and more ubiquitous, we would probably drop the `ensure_python` call in the future (near future?). So this issue can track that.
