### ISSUE TITLE
Refreshing to update diff?

### ISSUE THREAD

**Issue by rijobro** [jupyter/nbdime#558]
If I run `nbdiff-web` and then update the files, then clicking `Diff Files` will refresh the diff. It would be great if I could simply refresh the webpage. Instead the window just closes.

**Comment by vidartf** [comment]
You can add the flag `--persist`:
> --persist             prevent server shutting down on remote close request (when these would normally be supported).

The current behavior is the way it is so that the command exits when you close the browser tab. If there is a way to distinguish between a refresh and a close event in the browser, we could try to have this happen automatically, otherwise, `--persist` seems to be your best bet.

**Comment by rijobro** [comment]
That's great, thanks! I'll close, but feel free to re-open if you plan on investigating refresh vs close browser events.
