### ISSUE TITLE
_cell_marker_format yields incorrect styles

### ISSUE THREAD

**Issue by mlucool** [jupyter/nbdime#626]
https://github.com/jupyter/nbdime/blob/524aac24e1b1a4367f3673627161e5bcf62d8f90/nbdime/merging/strategies.py#L238 leads to incorrect styling (not bolded as intended) for `<<<<<<< local` I believe this is because of the following open tag `<`.  It seems like we should instead use  `<b>` tag.

![image](https://user-images.githubusercontent.com/1813603/186990260-1d86028d-4cf4-49d4-90d9-7dfbdfc0b9e1.png)

As a note `=======` does not look bold because the bolded version seems to just different placed. In the following image, the right pair is "bolded":
![image](https://user-images.githubusercontent.com/1813603/186990642-a045e328-2ea4-4e02-be86-5e289e1982d0.png)

Should we instead set a font size? This is 1.5em, not bold (`style="color:red; font-size: 1.5em"`):
![image](https://user-images.githubusercontent.com/1813603/186992191-e0744516-55fc-4d60-b7f0-a466f4f1967a.png)

OS: Windows
Browser: Chrome 104
JupyterLab: 3.4.3

**Comment by mlucool** [comment]
CC @vidartf in case you have any thoughts before I make a PR

**Comment by vidartf** [comment]
@mlucool It used to work well (https://github.com/jupyter/nbdime/pull/347) but I guess something changed in the markdown renderer? Using `<b>` is probably the best option, yes. I was wondering to myself if there was some good reason why `**` was used rather than `<b>` in the first place, but I can't remember/think of anything, and can't find anything in git history, so please go ahead! 👍
